# This is the Jekyll Config file - So, don't change it unless you know what you're doing.

safe:        true
auto:        true
server:      false
server_port: 4000
baseurl:     /parlour
repository:  https://github.com/wingnutart/parlour
url:         http://localhost:4000

source:      .
destination: ./_site
plugins:     _plugins

future:      true
lsi:         false
pygments:    true
markdown:    redcarpet
permalink:   pretty

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]